### ISSUE TITLE
Images for README

### ISSUE THREAD

**Issue by c-bata** [CyberAgent/cmaes#1]
## Visualizer

![himmelblau](https://user-images.githubusercontent.com/5564044/73486618-dac46880-43e8-11ea-8a2e-69d745f008b5.gif)
![quadratic](https://user-images.githubusercontent.com/5564044/73486619-dac46880-43e8-11ea-859d-5f8358ac8be9.gif)
![rosenbrock](https://user-images.githubusercontent.com/5564044/73486620-dac46880-43e8-11ea-9295-ec0bfa774655.gif)
![six-hemp-camel](https://user-images.githubusercontent.com/5564044/73486622-db5cff00-43e8-11ea-98fb-8246dbacab6d.gif)

## Benchmark

![rosenbrock](https://user-images.githubusercontent.com/5564044/73486735-0cd5ca80-43e9-11ea-9e6e-35028edf4ee8.png)
![six_hemp_camel](https://user-images.githubusercontent.com/5564044/73486738-0e9f8e00-43e9-11ea-8e65-d60fd5853b8d.png)
![himmelblau](https://user-images.githubusercontent.com/5564044/73486743-10695180-43e9-11ea-80d8-5b6f89104952.png)

**Comment by ha-mano** [comment]
## Visualizer
### CMA-ES with Margin
![CMA-ES](https://github.com/CyberAgentAILab/cmaes/assets/27720055/41d33c4b-b80b-42af-9f62-6d22f19dbae5)
![CMA-ESwM](https://github.com/CyberAgentAILab/cmaes/assets/27720055/9035deaa-6222-4720-a417-c31c765f3228)
### CatCMA
![CatCMA](https://github.com/CyberAgentAILab/cmaes/assets/27720055/f91443b6-d71b-4849-bfc3-095864f7c58c)

**Comment by ha-mano** [comment]
## Visualizer

### CatCMA with Margin

![Image](https://github.com/user-attachments/assets/ab6a0851-3d8f-47be-b82f-f917ce4bcdc2)

**Comment by ha-mano** [comment]
## Visualizer

### CatCMA with Margin

![Image](https://github.com/user-attachments/assets/d0c866f5-1c12-4f44-a862-af47bcd7dfb1)
