### ISSUE TITLE
question about the `tell` inferface

### ISSUE THREAD

**Issue by nmasahiro** [CyberAgent/cmaes#4]
I have a question about the `tell` interface.

I think it is more intuitive to use the solution in x space (i.e. ~N(m, σ^2 C)) as an argument,
but why do you use the solution in z space (i.e. ~N(0, I)) as an argument now?

**Comment by c-bata** [comment]
You are completely right. I'll fix it at https://github.com/c-bata/cmaes/pull/4.

**Comment by c-bata** [comment]
I merged https://github.com/c-bata/cmaes/pull/4. I'll this change at v0.2.0.

**Comment by c-bata** [comment]
Released.
https://pypi.org/project/cmaes/0.2.0/
