### ISSUE TITLE
Wrong definition of dim in get_warm_start_mgd

### ISSUE THREAD

**Issue by Yibinjiang** [CyberAgent/cmaes#97]
dim in "get_warm_start_mgd" is defined as dim = len(source_solutions[0]). Since source_solutions[0] is tuple, this dim is always 2. I'm assuming dim = len(source_solutions[0][0]), otherwise get_warm_start_mgd won't work for higher dimensional data.

**Comment by c-bata** [comment]
Good catch!! You are completely right. I fixed this bug at #98.

**Comment by c-bata** [comment]
I published v0.8.2 for this bugfix. Thank you for reporting!
https://github.com/CyberAgent/cmaes/releases/tag/v0.8.2
